Main : Server4.cpp Admin.h Client.h ClientThread.h Logger.h Message.h Server.h Server4.h ServerThread.h Socket.h Thread.h ClientThread.cpp Socket.cpp
	g++ -pthread Server4.cpp ClientThread.cpp Socket.cpp -o Main
